build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armhf: ghcr.io/home-assistant/armhf-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Coturn"
  org.opencontainers.image.description: "Coturn TURN/STUN server for WebRTC and VoIP NAT traversal"
  org.opencontainers.image.source: "https://github.com/MichalTorma/ha-coturn"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.documentation: "https://github.com/MichalTorma/ha-coturn/blob/main/README.md"
args:
  COTURN_VERSION: "4.7.0"
