name: "Coturn TURN/STUN Server"
description: "Coturn TURN/STUN server for WebRTC and VoIP NAT traversal"
version: "0.1.2"
slug: "coturn"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: manual
hassio_api: true
hassio_role: default
host_network: false
privileged: []
ports:
  3478/tcp: 3478
  3478/udp: 3478
  5349/tcp: 5349
  5349/udp: 5349
ports_description:
  3478/tcp: "STUN/TURN TCP"
  3478/udp: "STUN/TURN UDP"
  5349/tcp: "STUN/TURN over TLS/DTLS TCP"
  5349/udp: "STUN/TURN over TLS/DTLS UDP"
map:
  - config:rw
  - ssl:ro
options:
  listening_port: 3478
  tls_listening_port: 5349
  min_port: 49152
  max_port: 65535
  realm: "homeassistant.local"
  use_auth_secret: true
  static_auth_secret: ""
  username: ""
  password: ""
  cert_file: "fullchain.pem"
  pkey_file: "privkey.pem"
  log_level: 3
  verbose: false
  fingerprint: false
  use_stun_server: true
  use_turn_server: true
  deny_peer_ip: []
  allowed_peer_ip: []
  external_ip: ""
schema:
  listening_port: "port"
  tls_listening_port: "port"
  min_port: "port"
  max_port: "port"
  realm: "str"
  use_auth_secret: "bool"
  static_auth_secret: "password?"
  username: "str?"
  password: "password?"
  cert_file: "str?"
  pkey_file: "str?"
  log_level: "int(1,7)"
  verbose: "bool"
  fingerprint: "bool"
  use_stun_server: "bool"
  use_turn_server: "bool"
  deny_peer_ip: ["str"]
  allowed_peer_ip: ["str"]
  external_ip: "str?"
