name: "Coturn TURN/STUN Server"
description: "Coturn TURN/STUN server for WebRTC and VoIP NAT traversal"
version: "0.1.3"
slug: "coturn"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: manual
hassio_api: true
hassio_role: default
host_network: false
privileged: []
ports:
  3478/tcp: 3478
  3478/udp: 3478
  5349/tcp: 5349
  5349/udp: 5349
  # UDP ports for TURN relay traffic (subset of 49152-65535 range)
  49152/udp: 49152
  49153/udp: 49153
  49154/udp: 49154
  49155/udp: 49155
  49156/udp: 49156
  49157/udp: 49157
  49158/udp: 49158
  49159/udp: 49159
  49160/udp: 49160
  49161/udp: 49161
  49162/udp: 49162
  49163/udp: 49163
  49164/udp: 49164
  49165/udp: 49165
  49166/udp: 49166
  49167/udp: 49167
  49168/udp: 49168
  49169/udp: 49169
  49170/udp: 49170
  49171/udp: 49171
ports_description:
  3478/tcp: "STUN/TURN TCP"
  3478/udp: "STUN/TURN UDP"
  5349/tcp: "STUN/TURN over TLS/DTLS TCP"
  5349/udp: "STUN/TURN over TLS/DTLS UDP"
  49152/udp: "TURN relay port"
  49153/udp: "TURN relay port"
  49154/udp: "TURN relay port"
  49155/udp: "TURN relay port"
  49156/udp: "TURN relay port"
  49157/udp: "TURN relay port"
  49158/udp: "TURN relay port"
  49159/udp: "TURN relay port"
  49160/udp: "TURN relay port"
  49161/udp: "TURN relay port"
  49162/udp: "TURN relay port"
  49163/udp: "TURN relay port"
  49164/udp: "TURN relay port"
  49165/udp: "TURN relay port"
  49166/udp: "TURN relay port"
  49167/udp: "TURN relay port"
  49168/udp: "TURN relay port"
  49169/udp: "TURN relay port"
  49170/udp: "TURN relay port"
  49171/udp: "TURN relay port"
map:
  - config:rw
  - ssl:ro
options:
  listening_port: 3478
  tls_listening_port: 5349
  min_port: 49152
  max_port: 65535
  realm: "homeassistant.local"
  use_auth_secret: true
  static_auth_secret: ""
  username: ""
  password: ""
  cert_file: "fullchain.pem"
  pkey_file: "privkey.pem"
  log_level: 3
  verbose: false
  fingerprint: false
  use_stun_server: true
  use_turn_server: true
  deny_peer_ip: []
  allowed_peer_ip: []
  external_ip: ""
schema:
  listening_port: "port"
  tls_listening_port: "port"
  min_port: "port"
  max_port: "port"
  realm: "str"
  use_auth_secret: "bool"
  static_auth_secret: "password?"
  username: "str?"
  password: "password?"
  cert_file: "str?"
  pkey_file: "str?"
  log_level: "int(1,7)"
  verbose: "bool"
  fingerprint: "bool"
  use_stun_server: "bool"
  use_turn_server: "bool"
  deny_peer_ip: ["str"]
  allowed_peer_ip: ["str"]
  external_ip: "str?"
